[workspace]
resolver = "2"
members = ["crates/nagato_apply", "crates/nagato_cli", "crates/nagato_core"]

[workspace.package]
authors = ["dannycreations"]
edition = "2021"
license = "GPL"
repository = "https://github.com/dannycreations/Nagato"

[workspace.dependencies]
anyhow = "1.0.103"
assert_cmd = "2.2.2"
bstr = { version = "1.12.3", features = ["std"] }
clap = { version = "4.6.1", features = ["derive"] }
criterion = "0.8.2"
flate2 = "1.1.9"
hex = "0.4.3"
indoc = "2.0.7"
memchr = "2.8.2"
memmap2 = "0.9.11"
nagato_apply = { path = "crates/nagato_apply" }
nagato_core = { path = "crates/nagato_core" }
predicates = "3.1.4"
sha1 = "0.11.0"
tempfile = "3.27.0"
thiserror = "2.0.18"

[profile.dev]
codegen-units = 16
debug = 1
incremental = true

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = false
lto = true
opt-level = 3
panic = "abort"
split-debuginfo = "packed"
